import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { addPatient } from './dataService'; // Removed getPatients since it's not used here

export default function AddPatient() {
  const navigate = useNavigate();
  
  // 1. REMOVED 'id' from formData initialization. 
  // It will be auto-generated by dataService.js
  const [formData, setFormData] = useState({ name: '', age: '' });
  const [errors, setErrors] = useState({});

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // 2. REMOVED 'id' validation since the user no longer enters it
    if (!formData.name || !formData.age) {
        setErrors({ general: "All fields are required" });
        return;
    }
    
    // 3. Pass the data to dataService. 
    // dataService will automatically assign the scoped ID and doctorEmail before saving!
    addPatient(formData);
    navigate('/dashboard');
  };

  return (
    <div className="form-page">
      <div className="form-box">
        <h2>Add Patient</h2>
        {errors.general && <span className="error-text">{errors.general}</span>}
        <form onSubmit={handleSubmit}>
          
          {/* REMOVED the Patient ID input field completely */}
          
          <div className="input-group">
            <input 
              type="text" 
              placeholder="Full Name" 
              className="input-field" 
              onChange={e => setFormData({...formData, name: e.target.value})} 
              required 
            />
          </div>
          
          <div className="input-group">
            <input 
              type="number" 
              placeholder="Age" 
              className="input-field" 
              onChange={e => setFormData({...formData, age: e.target.value})} 
              required 
            />
          </div>
          
          <div className="action-buttons mt-1">
            <button type="submit" className="primary-btn">Save Patient</button>
            <button type="button" onClick={() => navigate('/dashboard')} className="secondary-btn">Cancel</button>
          </div>
          
        </form>
      </div>
    </div>
  );
}